import { MigrationInterface, QueryRunner } from 'typeorm';

export class FakePosts1641821067055 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      insert into post (title, text, "creatorId", "createdAt") values ('Switchable coherent project', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2021-02-19T17:20:21Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Compatible attitude-oriented utilisation', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2021-04-27T06:41:27Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Optimized dynamic orchestration', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2021-08-01T16:37:17Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Team-oriented disintermediate infrastructure', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2021-08-22T18:15:52Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Robust tertiary array', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2021-09-15T22:51:46Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Enterprise-wide methodical orchestration', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2021-10-10T08:47:33Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Polarised value-added moratorium', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2021-06-14T07:22:11Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Phased reciprocal middleware', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2021-10-30T04:03:46Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Self-enabling upward-trending matrix', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2021-06-22T00:46:57Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Organized interactive frame', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, '2021-10-21T04:13:00Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Focused interactive protocol', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1, '2021-04-14T04:37:21Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Robust scalable hub', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2021-06-20T17:55:41Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Digitized heuristic hierarchy', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2021-01-20T08:06:25Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Profit-focused 6th generation leverage', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-11-16T04:29:55Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Quality-focused systemic project', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2021-10-10T23:02:15Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Persistent fresh-thinking support', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2021-04-09T17:58:22Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Pre-emptive cohesive access', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2021-11-11T22:07:08Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Monitored 3rd generation firmware', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, '2021-04-12T04:55:04Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Exclusive bi-directional installation', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, '2021-01-31T16:19:21Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Distributed attitude-oriented function', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2021-11-27T04:22:53Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Centralized exuding toolset', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, '2022-01-02T22:04:09Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Re-contextualized foreground functionalities', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, '2021-06-19T18:46:10Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Focused disintermediate adapter', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2021-03-17T04:42:31Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Focused zero defect neural-net', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2021-06-30T00:56:59Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Persevering high-level conglomeration', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2021-09-06T09:35:30Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Robust disintermediate software', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2021-03-08T16:41:32Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Reactive interactive Graphic Interface', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2021-07-24T00:28:43Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Intuitive high-level adapter', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, '2021-05-27T00:47:14Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Team-oriented explicit methodology', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2021-12-05T05:31:01Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Cross-group actuating service-desk', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2021-10-21T08:44:32Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Function-based neutral moratorium', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2021-06-12T14:10:06Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Extended client-server database', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2021-09-21T19:31:44Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Synergized coherent leverage', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, '2021-10-16T22:18:35Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Open-architected didactic benchmark', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2021-06-29T05:27:59Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Networked full-range architecture', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1, '2021-08-02T07:31:16Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Compatible bi-directional matrices', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, '2021-08-18T00:57:43Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Customer-focused encompassing framework', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1, '2021-02-28T07:52:45Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Organized multimedia emulation', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-10-31T17:47:47Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Decentralized intermediate utilisation', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2021-09-21T11:45:44Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Team-oriented bandwidth-monitored system engine', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2021-10-23T11:31:52Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Digitized uniform complexity', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2021-12-05T22:56:52Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Reactive zero administration archive', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2021-12-25T18:31:49Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Grass-roots logistical focus group', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1, '2021-01-17T02:38:19Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Extended human-resource emulation', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2021-11-28T03:29:02Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Organized 3rd generation productivity', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2021-08-29T05:02:43Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Upgradable executive leverage', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2021-02-16T03:47:28Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Future-proofed multimedia capability', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2021-12-05T06:52:10Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Versatile mission-critical neural-net', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, '2021-11-06T12:56:30Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Switchable eco-centric secured line', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2021-11-19T21:53:19Z');
      insert into post (title, text, "creatorId", "createdAt") values ('Profound web-enabled synergy', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1, '2021-02-28T09:18:14Z');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
